// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webVTYSvize.Data;

#nullable disable

namespace webVTYSvize.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("webVTYSvize.Data.Hizmet", b =>
                {
                    b.Property<int>("idHizmet")
                        .HasColumnType("int");

                    b.Property<string>("hizmetTabloAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("hizmetTabloId")
                        .HasColumnType("int");

                    b.HasKey("idHizmet");

                    b.ToTable("Hizmet");
                });

            modelBuilder.Entity("webVTYSvize.Data.HizmetBilgisi", b =>
                {
                    b.Property<int>("idHizmetBilgisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("adi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("fiyat")
                        .HasColumnType("int");

                    b.Property<string>("resimUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idHizmetBilgisi");

                    b.ToTable("HizmetBilgisi");
                });

            modelBuilder.Entity("webVTYSvize.Data.Musteri", b =>
                {
                    b.Property<int>("idMusteri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("adi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("dogumTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("epostaAdresi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("soyadi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefonNumarasi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idMusteri");

                    b.ToTable("Musteri");
                });

            modelBuilder.Entity("webVTYSvize.Data.Otel", b =>
                {
                    b.Property<int>("idOtel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("HizmetBilgisi_idHizmetBilgisi")
                        .HasColumnType("int");

                    b.Property<string>("adres")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("puan")
                        .HasColumnType("double");

                    b.Property<string>("tema")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idOtel");

                    b.HasIndex("HizmetBilgisi_idHizmetBilgisi");

                    b.ToTable("Otel");
                });

            modelBuilder.Entity("webVTYSvize.Data.Rezervasyon", b =>
                {
                    b.Property<int>("idRezervasyon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Hizmet_idHizmet")
                        .HasColumnType("int");

                    b.Property<int>("Musteri_idMusteri")
                        .HasColumnType("int");

                    b.Property<int>("cocukSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("tarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("yetiskinSayısı")
                        .HasColumnType("int");

                    b.HasKey("idRezervasyon");

                    b.HasIndex("Musteri_idMusteri");

                    b.ToTable("Rezervasyon");
                });

            modelBuilder.Entity("webVTYSvize.Data.TekneTur", b =>
                {
                    b.Property<int>("idTekneTur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("HizmetBilgisi_idHizmetBilgisi")
                        .HasColumnType("int");

                    b.Property<string>("TurProgrami_idTurProgrami")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("idTekneTur");

                    b.HasIndex("HizmetBilgisi_idHizmetBilgisi");

                    b.HasIndex("TurProgrami_idTurProgrami");

                    b.ToTable("TekneTur");
                });

            modelBuilder.Entity("webVTYSvize.Data.TurProgrami", b =>
                {
                    b.Property<string>("idTurProgrami")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("baslangicKonumu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("baslangicTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("gunBes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("gunBir")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("gunDort")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("gunIki")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("gunUc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("guzergah")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("vizeDurumu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idTurProgrami");

                    b.ToTable("TurProgrami");
                });

            modelBuilder.Entity("webVTYSvize.Data.YurtdisiTur", b =>
                {
                    b.Property<int>("idYurtdisiTur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("HizmetBilgisi_idHizmetBilgisi")
                        .HasColumnType("int");

                    b.Property<string>("TurProgrami_idTurProgrami")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("idYurtdisiTur");

                    b.HasIndex("HizmetBilgisi_idHizmetBilgisi");

                    b.HasIndex("TurProgrami_idTurProgrami");

                    b.ToTable("YurtdisiTur");
                });

            modelBuilder.Entity("webVTYSvize.Data.Hizmet", b =>
                {
                    b.HasOne("webVTYSvize.Data.Rezervasyon", "rezervasyon")
                        .WithOne("hizmet")
                        .HasForeignKey("webVTYSvize.Data.Hizmet", "idHizmet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("rezervasyon");
                });

            modelBuilder.Entity("webVTYSvize.Data.Otel", b =>
                {
                    b.HasOne("webVTYSvize.Data.HizmetBilgisi", "hizmetBilgisi")
                        .WithMany()
                        .HasForeignKey("HizmetBilgisi_idHizmetBilgisi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hizmetBilgisi");
                });

            modelBuilder.Entity("webVTYSvize.Data.Rezervasyon", b =>
                {
                    b.HasOne("webVTYSvize.Data.Musteri", "Musteri")
                        .WithMany("Rezervasyonlar")
                        .HasForeignKey("Musteri_idMusteri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("webVTYSvize.Data.TekneTur", b =>
                {
                    b.HasOne("webVTYSvize.Data.HizmetBilgisi", "hizmetBilgisi")
                        .WithMany()
                        .HasForeignKey("HizmetBilgisi_idHizmetBilgisi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webVTYSvize.Data.TurProgrami", "turProgrami")
                        .WithMany()
                        .HasForeignKey("TurProgrami_idTurProgrami")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hizmetBilgisi");

                    b.Navigation("turProgrami");
                });

            modelBuilder.Entity("webVTYSvize.Data.YurtdisiTur", b =>
                {
                    b.HasOne("webVTYSvize.Data.HizmetBilgisi", "hizmetBilgisi")
                        .WithMany()
                        .HasForeignKey("HizmetBilgisi_idHizmetBilgisi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webVTYSvize.Data.TurProgrami", "turProgrami")
                        .WithMany()
                        .HasForeignKey("TurProgrami_idTurProgrami")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hizmetBilgisi");

                    b.Navigation("turProgrami");
                });

            modelBuilder.Entity("webVTYSvize.Data.Musteri", b =>
                {
                    b.Navigation("Rezervasyonlar");
                });

            modelBuilder.Entity("webVTYSvize.Data.Rezervasyon", b =>
                {
                    b.Navigation("hizmet");
                });
#pragma warning restore 612, 618
        }
    }
}
